# =============================================
# PostgreSQL - Tienda Musical
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5433/7502613001_13_tienda_musica
spring.datasource.username=postgres
spring.datasource.password=#Gonza
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# =============================================
# Servidor
# =============================================
server.port=8080
